In [178]:
import numpy as np
import pandas as pd

In [179]:
np.__version__

'1.21.5'

In [180]:
df = pd.read_csv("data.csv")

In [181]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [182]:
df.count().max()

11914

In [183]:
df.Make.value_counts()[0:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

In [184]:
df[df.Make == "Audi"].Model.value_counts().count()

34

In [185]:
df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [186]:
df["Engine Cylinders"].median()

6.0

In [187]:
a = df["Engine Cylinders"].mode()
a

0    4.0
Name: Engine Cylinders, dtype: float64

In [188]:
df["Engine Cylinders"].isna().sum()

30

In [189]:
df["Engine Cylinders"] = df["Engine Cylinders"].fillna(4)

In [190]:
df["Engine Cylinders"].isna().sum()

0

In [191]:
df["Engine Cylinders"].median()

6.0

In [192]:
df1 = df[df["Make"] == "Lotus"]

In [193]:
df1 = df1[["Engine HP", "Engine Cylinders"]]

In [194]:
df1

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [195]:
df1.drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [196]:
X = np.array(df1.drop_duplicates())

In [197]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [198]:
P = X.T
P

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [199]:
XTX = P.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [200]:
XI = np.linalg.inv(XTX)
XI

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [201]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [202]:
w = (XI.dot(P)).dot(y)

In [203]:
w

array([  4.59494481, -63.56432501])