In [1]:
import numpy as np

In [2]:
np.ones(3)

array([1., 1., 1.])

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.full(23,1.234)

array([1.234, 1.234, 1.234, 1.234, 1.234, 1.234, 1.234, 1.234, 1.234,
       1.234, 1.234, 1.234, 1.234, 1.234, 1.234, 1.234, 1.234, 1.234,
       1.234, 1.234, 1.234, 1.234, 1.234])

In [9]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [10]:
np.array([2,4,6,8,1,3,5,7,9])

array([2, 4, 6, 8, 1, 3, 5, 7, 9])

In [11]:
b = np.array([2,4,6,8,1,3,5,7,9])

In [12]:
b[3]

8

In [13]:
b[3] = 19
b[3]

19

In [14]:
b[2:5]

array([ 6, 19,  1])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [17]:
np.arange(1,53,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52])

In [19]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [25]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [21]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
a = np.array([[[11,12,13,14,15],[6,7,8,9,0],[1,2,3,4,5]],[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]]])

In [41]:
a

array([[[11, 12, 13, 14, 15],
        [ 6,  7,  8,  9,  0],
        [ 1,  2,  3,  4,  5]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9,  0],
        [11, 12, 13, 14, 15]]])

In [42]:
a.ndim

3

In [43]:
a[1]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [44]:
a[1,2]

array([11, 12, 13, 14, 15])

In [45]:
a[1,2,3]

14

In [46]:
a[0:,1:,:2]

array([[[ 6,  7],
        [ 1,  2]],

       [[ 6,  7],
        [11, 12]]])

In [47]:
a[0:,1:,:2] = np.array([[[12,14],[2,4]],[[18,21],[22,24]]])

In [48]:
a

array([[[11, 12, 13, 14, 15],
        [12, 14,  8,  9,  0],
        [ 2,  4,  3,  4,  5]],

       [[ 1,  2,  3,  4,  5],
        [18, 21,  8,  9,  0],
        [22, 24, 13, 14, 15]]])

In [50]:
a[:,:,:2]

array([[[11, 12],
        [12, 14],
        [ 2,  4]],

       [[ 1,  2],
        [18, 21],
        [22, 24]]])

In [51]:
a[:,:,:2] = [[[23,24],[33,34],[43,44]],[[53,54],[63,64],[73,74]]]

In [52]:
a

array([[[23, 24, 13, 14, 15],
        [33, 34,  8,  9,  0],
        [43, 44,  3,  4,  5]],

       [[53, 54,  3,  4,  5],
        [63, 64,  8,  9,  0],
        [73, 74, 13, 14, 15]]])

In [53]:
a[1,2,3]

14

In [30]:
c = np.array([[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]])

In [31]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [32]:
c.ndim

2

In [33]:
d = np.array([1,2,3,4,5,6,7,8,9])

In [35]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
d.ndim

1

In [54]:
np.random.rand()

0.39958542219774773

In [55]:
np.random.rand(12)

array([0.52607805, 0.66519257, 0.99235631, 0.91631617, 0.11820063,
       0.36211855, 0.22965655, 0.60541617, 0.20300176, 0.4189567 ,
       0.10506872, 0.86659231])

In [56]:
np.random.rand(12,3)

array([[0.80860127, 0.86366301, 0.8212484 ],
       [0.69917862, 0.65530175, 0.29772719],
       [0.33358738, 0.71808464, 0.99492103],
       [0.69342836, 0.76659264, 0.18202346],
       [0.32079105, 0.82427252, 0.53370213],
       [0.53909047, 0.93393352, 0.98639168],
       [0.72504139, 0.20125077, 0.22909121],
       [0.48480126, 0.06692154, 0.4827997 ],
       [0.01123862, 0.59762433, 0.97960378],
       [0.33505676, 0.89582102, 0.78403025],
       [0.02956305, 0.20561189, 0.39178887],
       [0.94070892, 0.10195377, 0.67121301]])

In [58]:
np.random.rand(13,4,5)

array([[[6.52260248e-01, 7.09018586e-01, 3.68128965e-01, 6.82381469e-01,
         3.71580297e-01],
        [7.81004396e-01, 6.88127918e-01, 1.32883181e-01, 1.19865786e-01,
         5.06863853e-01],
        [8.05718698e-01, 3.16880958e-01, 7.60463657e-01, 3.47977248e-01,
         7.49430150e-02],
        [7.38548763e-02, 3.23444018e-01, 6.94018263e-01, 8.51954850e-01,
         1.45317739e-01]],

       [[8.28273023e-01, 9.67744066e-01, 6.60584045e-01, 5.93695510e-02,
         1.65232042e-01],
        [9.12046256e-01, 3.36800600e-01, 6.28779607e-01, 5.18748348e-01,
         9.50278684e-01],
        [5.63693916e-01, 7.64090809e-03, 4.34253729e-01, 9.57423065e-01,
         7.35881858e-01],
        [3.94288701e-01, 8.58196168e-01, 1.39928702e-01, 2.87371293e-01,
         2.97799249e-01]],

       [[2.44575963e-01, 2.78794971e-01, 8.85195705e-03, 8.24466768e-01,
         3.62071147e-01],
        [7.33779677e-01, 2.38868370e-01, 1.72207984e-01, 3.31194454e-01,
         4.00296625e-01],
      

In [60]:
np.random.seed(3)
np.random.rand(2,3,4,5,6)

array([[[[[5.50797903e-01, 7.08147823e-01, 2.90904739e-01,
           5.10827605e-01, 8.92946954e-01, 8.96293089e-01],
          [1.25585310e-01, 2.07242878e-01, 5.14672033e-02,
           4.40809844e-01, 2.98762109e-02, 4.56833224e-01],
          [6.49144048e-01, 2.78487283e-01, 6.76254902e-01,
           5.90862817e-01, 2.39818824e-02, 5.58854088e-01],
          [2.59252447e-01, 4.15101197e-01, 2.83525082e-01,
           6.93137918e-01, 4.40453718e-01, 1.56867738e-01],
          [5.44649018e-01, 7.80314765e-01, 3.06363532e-01,
           2.21957884e-01, 3.87971258e-01, 9.36383650e-01]],

         [[9.75995422e-01, 6.72383676e-01, 9.02834109e-01,
           8.45750871e-01, 3.77994041e-01, 9.22170089e-02],
          [6.53410903e-01, 5.57840762e-01, 3.61564763e-01,
           2.25054505e-01, 4.06519916e-01, 4.68940249e-01],
          [2.69235578e-01, 2.91792774e-01, 4.57686399e-01,
           8.60533913e-01, 5.86252904e-01, 2.83487862e-01],
          [2.77977507e-01, 4.54622076e-01, 2.0

In [66]:
np.random.randint(44)

23

In [72]:
np.random.seed(2)
np.random.randint(low = 0, high = 100, size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [68]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [69]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [73]:
a

array([[[23, 24, 13, 14, 15],
        [33, 34,  8,  9,  0],
        [43, 44,  3,  4,  5]],

       [[53, 54,  3,  4,  5],
        [63, 64,  8,  9,  0],
        [73, 74, 13, 14, 15]]])

In [75]:
a + 1

array([[[24, 25, 14, 15, 16],
        [34, 35,  9, 10,  1],
        [44, 45,  4,  5,  6]],

       [[54, 55,  4,  5,  6],
        [64, 65,  9, 10,  1],
        [74, 75, 14, 15, 16]]])

In [76]:
a

array([[[23, 24, 13, 14, 15],
        [33, 34,  8,  9,  0],
        [43, 44,  3,  4,  5]],

       [[53, 54,  3,  4,  5],
        [63, 64,  8,  9,  0],
        [73, 74, 13, 14, 15]]])

In [77]:
a * 5

array([[[115, 120,  65,  70,  75],
        [165, 170,  40,  45,   0],
        [215, 220,  15,  20,  25]],

       [[265, 270,  15,  20,  25],
        [315, 320,  40,  45,   0],
        [365, 370,  65,  70,  75]]])

In [92]:
a

array([[[23, 24, 13, 14, 15],
        [33, 34,  8,  9,  0],
        [43, 44,  3,  4,  5]],

       [[53, 54,  3,  4,  5],
        [63, 64,  8,  9,  0],
        [73, 74, 13, 14, 15]]])

In [93]:
d = a + 10

In [94]:
d

array([[[33, 34, 23, 24, 25],
        [43, 44, 18, 19, 10],
        [53, 54, 13, 14, 15]],

       [[63, 64, 13, 14, 15],
        [73, 74, 18, 19, 10],
        [83, 84, 23, 24, 25]]])

In [95]:
d[:,:,:2] = d[:,:,:2] - 30

In [96]:
d

array([[[ 3,  4, 23, 24, 25],
        [13, 14, 18, 19, 10],
        [23, 24, 13, 14, 15]],

       [[33, 34, 13, 14, 15],
        [43, 44, 18, 19, 10],
        [53, 54, 23, 24, 25]]])

In [97]:
d[1,:,:2] = d[1,:,:2] - 30

In [98]:
d

array([[[ 3,  4, 23, 24, 25],
        [13, 14, 18, 19, 10],
        [23, 24, 13, 14, 15]],

       [[ 3,  4, 13, 14, 15],
        [13, 14, 18, 19, 10],
        [23, 24, 23, 24, 25]]])

In [103]:
e = (a + d) * 2

In [104]:
e

array([[[ 52,  56,  72,  76,  80],
        [ 92,  96,  52,  56,  20],
        [132, 136,  32,  36,  40]],

       [[112, 116,  32,  36,  40],
        [152, 156,  52,  56,  20],
        [192, 196,  72,  76,  80]]])

In [105]:
f = e // 3

In [106]:
f

array([[[17, 18, 24, 25, 26],
        [30, 32, 17, 18,  6],
        [44, 45, 10, 12, 13]],

       [[37, 38, 10, 12, 13],
        [50, 52, 17, 18,  6],
        [64, 65, 24, 25, 26]]])

In [107]:
g = f % 10

In [108]:
g

array([[[7, 8, 4, 5, 6],
        [0, 2, 7, 8, 6],
        [4, 5, 0, 2, 3]],

       [[7, 8, 0, 2, 3],
        [0, 2, 7, 8, 6],
        [4, 5, 4, 5, 6]]])

In [109]:
h = e - f

In [110]:
h

array([[[ 35,  38,  48,  51,  54],
        [ 62,  64,  35,  38,  14],
        [ 88,  91,  22,  24,  27]],

       [[ 75,  78,  22,  24,  27],
        [102, 104,  35,  38,  14],
        [128, 131,  48,  51,  54]]])

In [112]:
g >= 4

array([[[ True,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [ True,  True, False, False, False]],

       [[ True,  True, False, False, False],
        [False, False,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [113]:
(e - f ) == h

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [114]:
g[g % 10 > h % 10]

array([7, 5, 6, 7, 6, 5, 7, 7, 6, 5, 5, 6])

In [116]:
g.min()

0

In [117]:
h.min()

14

In [118]:
h.max()

131

In [119]:
g.max()

8

In [120]:
h.sum()

1622

In [121]:
g.sum()

134

In [122]:
g.std()

2.5525586292102194

In [123]:
g.mean()

4.466666666666667

In [124]:
h.mean()

54.06666666666667

In [125]:
h.std()

31.812925395540447